package java_cup.runtime;

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 07 10:55:21 CET 2006
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class tokens {
  /* terminals */
  public static final int DISTINTO = 25;
  public static final int FUNCTION = 8;
  public static final int MULT = 22;
  public static final int CONST = 5;
  public static final int PAR_CER = 15;
  public static final int RESTA = 19;
  public static final int DOS_PUNTOS = 16;
  public static final int NUM_CONST = 21;
  public static final int COM_PARAM = 37;
  public static final int CTE_LITERAL = 39;
  public static final int COM_CORTO = 34;
  public static final int NOT = 29;
  public static final int MENORIGUAL = 24;
  public static final int AND = 30;
  public static final int IGUAL = 26;
  public static final int COM_LARGO = 35;
  public static final int RECORD = 10;
  public static final int TYPE = 9;
  public static final int OR = 31;
  public static final int PAR_ABR = 14;
  public static final int COM_RETORNO = 38;
  public static final int DIV = 33;
  public static final int BEGIN = 3;
  public static final int SUMA = 18;
  public static final int ID = 20;
  public static final int MAYORIGUAL = 28;
  public static final int EOF = 0;
  public static final int ASIG = 17;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 13;
  public static final int MENOR = 23;
  public static final int MOD = 32;
  public static final int PCOMA = 11;
  public static final int MAYOR = 27;
  public static final int COM_AUTOR = 36;
  public static final int PUNTO = 12;
  public static final int WHILE = 41;
  public static final int END = 4;
  public static final int VAR = 6;
  public static final int PROCEDURE = 7;
  public static final int DO = 40;
  public static final int LEXERROR = 42;

  /* non terminals */
  static final int udtype = 39;
  static final int proc_call = 33;
  static final int simpvalue = 9;
  static final int fact = 24;
  static final int op_comp = 29;
  static final int asig = 20;
  static final int $START = 0;
  static final int dcllist = 3;
  static final int blq = 2;
  static final int superexp = 23;
  static final int defvar = 11;
  static final int defvarlist = 12;
  static final int sent = 19;
  static final int deftype = 37;
  static final int defcte = 7;
  static final int superfact = 25;
  static final int wloop = 40;
  static final int term = 26;
  static final int formal_param = 17;
  static final int varlist = 13;
  static final int comment = 5;
  static final int subpcomment = 18;
  static final int id = 21;
  static final int deffun = 15;
  static final int sentlist = 4;
  static final int prg = 1;
  static final int dcllist_blq = 35;
  static final int op_mult = 30;
  static final int op_adit = 28;
  static final int formal_paramlist = 16;
  static final int ctelist = 8;
  static final int superterm = 27;
  static final int subpparamlist = 31;
  static final int commentlist = 10;
  static final int typelist = 38;
  static final int exeblq = 34;
  static final int defproc = 14;
  static final int exp = 22;
  static final int explist = 32;
  static final int dcl = 6;
  static final int dcl_blq = 36;
}

